TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid

Documentation/6-Persistence/4-use-foreign-data-sources.rst

i just added the missing brackes. for the columns

added missing Brackets

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

Fixed a word at the wrong place
Changed `Tx_Extbase_Validation_Validator_ValidatorInterface ` to `Tx_Extbase_Validation_Validator_AbstractValidator` where needed
Changed `IsValid` to `isValid` (case)
Added code snippet of the email address validator

Fixed documentation bugs

---

Documentation/0-Introduction/5-thanks.rst

At least Google seems to think Kasper's last name is spelled with a j :)
Also, I have no idea why it says the last line here is different. I didn't change anything there, just the spelling of Kasper's last name.

Kasper Skårhøy -> Kasper Skårhøj

---

Documentation/2-BasicPrinciples/Index.rst

Some of this is subjective, but it seems more natural, at least to me.

Minor grammatical fixes

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

Replaced Tx_Extbase_Utility_Localization with \TYPO3\CMS\Extbase\Utility\LocalizationUtility

Namespaced Tx_Extbase_Utility_Localization

---

Documentation/10-Outlook/4-Property-mapping.rst
Documentation/10-Outlook/Index.rst

* As nothing was documented before

[FEATURE] Provide basic documentation about property mapping

---

Documentation/10-Outlook/2-Backend-modules.rst

Update the old extension utility class name to the namespaced version and register the module with the new vendor.package format

Use namespaced ExtensionUtility

---

Documentation/8-Fluid/1-basic-concepts.rst

Introduce namespaced FQCNs and replace non existent f:form.textbox with f:form.textfield

Update to namespaces and fix form.textbox

---

Documentation/6-Persistence/Index.rst

;)
(Last line change is most likely a "new line at end of file" automatically generated by github)

Add missing word "is" in persistence index docs

---

Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst

File: Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
Original link: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/6-Persistence/5-modeling-the-class-hierarchy.html

Replace t3lib_div with GeneralUtility (FQCN)

---

Documentation/2-BasicPrinciples/1-Object-oriented Programming-in-PHP.rst

Fixes this weird love for commas.

Fix commas

---

Documentation/4-FirstExtension/3-create-the-domain-model.rst
Documentation/4-FirstExtension/4-make-products-persistent.rst
Documentation/4-FirstExtension/5-controlling-the-flow.rst
Documentation/4-FirstExtension/6-adding-the-template.rst

Here you go :)
followup of #93

[TASK] use proper :php: for inline classes

---

Documentation/8-Fluid/7-using-boolean-conditions.rst

Not sure, but I think when there are 3 of these something must be wrong, I'm just assuming this one is the wrong one!?

Delete one " (too many)

---

Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst

ActionCotroller -> ActionController

---

Documentation/2-BasicPrinciples/1-Object-oriented Programming-in-PHP.rst

* at Classes and Objects 
* NULL instead of NUL
* at Constructor 
* added Code Reminder

Typo and reminder for code example

---

Documentation/0-Introduction/1-short-history.rst
Documentation/0-Introduction/3-structure.rst
Documentation/0-Introduction/Index.rst

Spellchecked chapter 0 for american english
Changed a textrole

Typo fix and change spelling to american english

---

Documentation/2-BasicPrinciples/1-Object-oriented Programming-in-PHP.rst
Documentation/2-BasicPrinciples/2-Domain-Driven-Design.rst
Documentation/2-BasicPrinciples/3-Model-View-Controller-in-Extbase.rst
Documentation/2-BasicPrinciples/4-Test-Driven-Development.rst
Documentation/2-BasicPrinciples/5-Conclusion.rst
Documentation/2-BasicPrinciples/Index.rst

Changed textroles and backticks.
Deleted a redundant sentence in Test Driven Development.
Spellcheck for american english

Fixes in chapter 2

---

Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst

makeInstance has a leading backslash, which is not allowed anymore.
Also t3lib_div does not exist anymore.

Fix makeInstance

---

Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst

changed "discarded" to "placed"

---

Documentation/1-Installation/6-more-helpful-extensions.rst

[BUGFIX] links to git instead of svn

---

Documentation/3-BlogExample/Index.rst
Documentation/6-Persistence/3-implement-individual-database-queries.rst

See: https://forge.typo3.org/issues/80380
See: https://review.typo3.org/#/c/53658/

[TASK] Extend individual query chapter by resolveDistinctEntities

---

Documentation/1-Installation/6-more-helpful-extensions.rst
Documentation/2-BasicPrinciples/Index.rst

I'm trying to clarify some things as I go through the docs. Hope it helps.

Grammar & spelling

---

Documentation/1-Installation/3-configuring-your-ide.rst

Adapt to current TYPO3 Coding Guidelines which follow the PSR-2-standard:
https://docs.typo3.org/typo3cms/CodingGuidelinesReference/PhpFileFormatting/GeneralRequirementsForPhpFiles/Index.html#whitespace-and-indentation

Update indention for spaces instead of tabs

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

Replace old @dontvalidate with @ignorevalidation - 
@dontvalidate was syntax of the old propertymapper.

Replace old @dontvalidate with @ignorevalidation

---

Documentation/4-FirstExtension/4-make-products-persistent.rst

"we don't have to thought about..." =>  "we don't have to think about..."

Corrected a word.

---

Documentation/b-ExtbaseReference/Index.rst

replace ext_tables.php by Configuration/TCA/Overrides/tt_content.php

The file ext_tables.php is not used any more.

---

Documentation/b-ExtbaseReference/Index.rst

Replace 'Vendor.ExtKey' by a term which uses a variable of the extension key.

there is no term 'Vendor.ExtKey'

---

Documentation/b-ExtbaseReference/Index.rst

make it more clear what the plugin name is

---

Documentation/10-Outlook/3-Command-controllers.rst

Includes.txt was not correctly included, remove waste 'g'

Fix basic include of Includes.txt

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

information is always singular.

"Those information"

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

Make it clear that the method findAll is already part of the Repository class.

findAll is part of Repository

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

It is necessary to know that the result is of type QueryResultInterface

add comments to findAll

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

findAll does not find anything. It is helpful to give the necessary extension setup here. Otherwise it is confusing why this does not work.

add missing info for findAll

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

The findByUid method should be listed here as well.

add Repository findByUid method

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst

by calling configurePlugin directly the example gets clearer

removed unnecessary call_user_func

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

a misplaced quote which causes wrong rendering of the code-color

remove a misplaced quote

---

Documentation/5-Domain/1-the-application-domain.rst

TASK: Fix wrong indentation in list

---

Documentation/10-Outlook/1-Creating-an-extension-with-the-kickstarter.rst
Documentation/10-Outlook/3-Command-controllers.rst
Documentation/2-BasicPrinciples/1-Object-oriented Programming-in-PHP.rst
Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/8-Fluid/10-template-creation-by-example.rst
Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst
Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst
Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

also fix typos and wrong rst syntax in many places

Add missing code examples

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst
Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst

Provide up to date information about writing custom ViewHelper.
fixes https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/180

Feature: Update section about custom ViewHelper

---

Documentation/4-FirstExtension/4-make-products-persistent.rst

Changed the Position from the Important Box and the XML Language Code

4-make-products-persistent.rst

---

Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst

=> was throwing a php error. The value must still be inside brackets [], and probably without the comma.

Corrected example code

---

Documentation/6-Persistence/2-configure-the-backends-inputforms.rst

fix quotation marks

---

Documentation/3-BlogExample/12-automatic-persistence-of-the-domain-logic.rst
Documentation/3-BlogExample/5-Get-Blog-from-the-Repository.rst

Discard sidebars because of layout problems

---

Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

This is a new PR for the PR #263 from @hasenbalg with resolved merge conflicts.

Mainly typos and comma fixes II

---

Documentation/0-Introduction/Index.rst

- Reduce redundancy in the text. Some things were said more than once in similar words
- Language improvements
- Add a note with review information to help with systematic review and to help
users see at a glance which pages are outdated
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/73

Improve Introduction chapter

---

Documentation/1-Installation/1-configuring-the-server.rst
Documentation/Settings.cfg

- rename title because server implies some remote server
- add information about ddev
- add header with review information
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/73

Improve installation page

---

Documentation/Index.rst
Documentation/Settings.cfg
Documentation/Sitemap/Index.rst
Documentation/Targets.rst

- add status (outdated) to start page.
- remove date of last rendering because that is already in footer
- add version
- add language
- add information about contribution to start page

Update start page

---

Documentation/4-FirstExtension/5-controlling-the-flow.rst

Fix typos and difficult formulations.

Improve readability in 5-controlling-the-flow

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst

Fix typos and difficult formulations

Improve readability in 7-configuring-the-plugin

---

Documentation/9-CrosscuttingConcerns/3-programming-secure-extensions.rst

Add security mention about manipulation of identity field value to prevent data replacement by an attacker

Security mention for identity field

---

Documentation/9-CrosscuttingConcerns/3-programming-secure-extensions.rst

* Also add possibility for named references.
* Also strip unnecessary underlines.

Make headlines upper camel case

---

Documentation/9a-Configuration/Index.rst
Documentation/Index.rst

To give some context, a chapter "Configuration" is added. This gives an
overview over possibilities and links to other manuals where the concepts
are explained in more detail.
Resolves: #281

Document switchableControllerActions

---

Documentation/9a-Configuration/Index.rst
Documentation/Index.rst

To give some context, a chapter "Configuration" is added. This gives an
overview over possibilities and links to other manuals where the concepts
are explained in more detail.
Resolves: #281

Document switchableControllerActions (8.7)

---

Documentation/9a-Configuration/Index.rst
Documentation/Index.rst

To give some context, a chapter "Configuration" is added. This gives an
overview over possibilities and links to other manuals where the concepts
are explained in more detail.
Resolves: #281

Document switchableControllerActions (9.5)

---

Documentation/10-Outlook/5-error-action.rst
Documentation/Index.rst

FEATURE: Document error action behaviour

---

Documentation/8-Fluid/2-using-different-output-formats.rst

Resolves: #284
Releases: 9.5, master

FEATURE: Add documentation for built in JsonView

---

Documentation/b-ExtbaseReference/Index.rst

Resolves: #282
Releases: 9.5, master

Add annotation reference

---

Documentation/8-Fluid/7-using-boolean-conditions.rst

Also removed a couple of sentences that did not make sense.

Remove incorrect information about booleans

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst
Documentation/9-CrosscuttingConcerns/3-programming-secure-extensions.rst

Language improvements for security chapter

---

Documentation/4-FirstExtension/1-the-example-extension.rst
Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
Documentation/4-FirstExtension/3-create-the-domain-model.rst
Documentation/4-FirstExtension/4-make-products-persistent.rst
Documentation/4-FirstExtension/5-controlling-the-flow.rst
Documentation/4-FirstExtension/6-adding-the-template.rst
Documentation/4-FirstExtension/7-configuring-the-plugin.rst
Documentation/4-FirstExtension/Index.rst

Rework chapter 4 (master)

---

Documentation/3-BlogExample/4-and-action.rst

see https://forge.typo3.org/issues/76876

[TASK] Update documentation and reference to full example

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

See this 5 year old feature changelog:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/42813/

Changes in Individual Database Queries chapter

---

Documentation/2-BasicPrinciples/Index.rst

Fixed typo

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

I suspect this is the correct link?

[DOCS] Update link to TYPO3 API

---

Documentation/3-BlogExample/Index.rst

Add a link target for "chapter 4"

Add a link target for "chapter 4"

---

Documentation/6-Persistence/2a-creating-the-repositories.rst

Change "Chapter 3" in actual link existing link to the Chapter

Change "Chapter 3" in actual link

---

Documentation/3-BlogExample/11-Alternative-route-creating-a-new-posting.rst

Link mentioned chapter 9 in https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/3-BlogExample/11-Alternative-route-creating-a-new-posting.html

Link mentioned chapter 9

---

Documentation/3-BlogExample/6-An-excursion-to-the-database.rst

Correct phrase "Later" to "Later on"

Correct phrase "Later" to "Later on"

---

.vscode/settings.json
Documentation/6-Persistence/1-prepare-the-database.rst
Documentation/6-Persistence/2-configure-the-backends-inputforms.rst
Documentation/6-Persistence/2a-creating-the-repositories.rst
Documentation/6-Persistence/3-implement-individual-database-queries.rst
Documentation/6-Persistence/Index.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/7-Controllers/3-Configuring-the-behavior-of-the-extension.rst

Changes in wording

---

Documentation/6-Persistence/2-configure-the-backends-inputforms.rst
Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

[TASK] Replace EXT:lang references

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

[TASK] Add info about registering validators

---

Documentation/6-Persistence/1-prepare-the-database.rst

[TASK] Remove t3ver_id reference

---

Documentation/9a-Configuration/Index.rst

See Core Deprecation 89463
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845

[TASK] Remove switchableControllerActions

---

Documentation/b-ExtbaseReference/Index.rst

[TASK] Qualify pre-requisite for property injection

---

Documentation/6-Persistence/1-prepare-the-database.rst

See Core Breaking 89137
Releases: 11.0

[TASK] Remove t3ver_tstamp & t3ver_count

---

Documentation/10-Outlook/6-dispatching.rst
Documentation/3-BlogExample/10-Returning-the-result-to-TYPO3.rst
Documentation/3-BlogExample/3-calling-the-extension.rst
Documentation/3-BlogExample/8-Back-in-the-controller.rst
Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/7-Controllers/Index.rst
Documentation/b-ExtbaseReference/Index.rst

See Core Breaking 92502
Releases: 11.0

[TASK] Update Response Handling to PSR-7

---

Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst

[TASK] Remove fluid paginator widget reference

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst

See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html

[TASK] Remove TYPO3_REQUESTTYPE and TYPO3_MODE

---

Documentation/10-Outlook/6-dispatching.rst
Documentation/3-BlogExample/11-Alternative-route-creating-a-new-posting.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst
Documentation/b-ExtbaseReference/Index.rst

.. and deprecate forward()
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92815-IntroduceForwardResponseForExtbase.html

[FEATURE] Introduce ForwardResponse

---

Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst

Updated code example for Extbase class / table mapping rrelated to #87623 (Replace config.persistence.classes typoscript configuration).

Update class mapping example (modelling the class hierarchy)

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

Releases: master, 10.4, 9.5, 8.7

Directly link to validation API

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

See (among others) core issue #89938 

[TASK] Update language handling to site / context based handling

---

Documentation/b-ExtbaseReference/Index.rst

[TASK] Remove @Inject annotation

---

Documentation/Index.rst
Documentation/c-FAQ/Index.rst

http://wiki.typo3.org/Extbase_und_Fluid_FAQ
refs: https://github.com/TYPO3-Documentation/T3DocTeam/issues/154

Migrate Wiki content: Extbase_und_Fluid_FAQ

---

Documentation/8-Fluid/1a-inline-syntax.rst

Releases master, 10.4
@resolves #219

Added link to fluidconverter

---

Documentation/3-BlogExample/2-the-stations-of-the-journey.rst

I think that this description is already for TYPO3 11. This cannot be seen in the extension for TYPO3 10.

Include the ToDo part

---

Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst

[DOCU] Update class mapping segment to v10 state

---

Documentation/3-BlogExample/11-Alternative-route-creating-a-new-posting.rst

Fix wrong usage of IgnoreValidation annotation

---

Documentation/8-Fluid/1-basic-concepts.rst

I assume here is a missing  link to wikipedia instead of the <remark> Tags?

Remove the remark tag with a Link

---

Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst

See https://github.com/FriendsOfTYPO3/blog_example/blob/master/Resources/Private/Templates/Blog/Index.html

update the code

---

Documentation/b-ExtbaseReference/Index.rst

Add small explanation and example.
That way it should be possible to make use of this feature in custom
extensions.
Releases: master, 10.4
Relates: #393

Document missing TypeInterface feature

---

Documentation/4-FirstExtension/1-the-example-extension.rst
Documentation/4-FirstExtension/Index.rst

There has already been the blog example as the first extension.

"first extension" is a bad title

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

See Slack Documentation from yesterday. Simon Gilli

There is no document "validation API".

---

Documentation/6-Persistence/2-configure-the-backends-inputforms.rst

The renderType needs to be defined, to make it work like in the image.

Update Missing renderType in configure inputforms

---

Documentation/CodeSnippets/StyleguideCode/ValidatorInterface.rst.txt

refs https://github.com/TYPO3-Documentation/t3docs-screenshots/pull/188

[TASK] Update images for TYPO3 11.4-dev

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst

Corrected the vendor name to the correct vendor in the example.

Update 7-configuring-the-plugin.rst, Corrected vendor name

---

Documentation/8-Fluid/2-using-different-output-formats.rst

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

[Feature] #90347 - Enable recursive transformation of properties in JsonView

---

Documentation/10-Outlook/4-Property-mapping.rst
Documentation/10-Outlook/6-dispatching.rst
Documentation/6-Persistence/2a-creating-the-repositories.rst

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

[DEPRECATION]  #94619 - Extbase ObjectManager

---

Documentation/8-Fluid/9-using-php-based-views.rst

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

[Deprecation] #94991 - Extbase AbstractView

---

Documentation/b-ExtbaseReference/Index.rst

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95222-ExtbaseViewInterface.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1522

[Deprecation] #95222 - Extbase ViewInterface

---

Documentation/6-Persistence/2a-creating-the-repositories.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

See TYPO3-Documentation/T3DocTeam#164 for details.

[TASK] Disable all dummy urls with `:samp:`

---

Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
Documentation/Settings.cfg
Documentation/a-CodingGuidelines/Index.rst

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Important-95647-ComposerInstallationsAndExtensionUsage.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
releases: master, 11.5

Important: #95647 - Composer installations and extension usage

---

Documentation/10-Outlook/6-dispatching.rst
Documentation/6-Persistence/2a-creating-the-repositories.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst
Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

See TYPO3-Documentation/T3DocTeam#165 for details.

[TASK] Unify top-level domain of dummy urls

---

Documentation/5-Domain/Index.rst
Documentation/6-Persistence/3-implement-individual-database-queries.rst

See TYPO3-Documentation/T3DocTeam#166 for details.

[TASK] Unify placeholder syntax

---

Documentation/1-Installation/Index.rst
Documentation/3-BlogExample/Index.rst
Documentation/9-CrosscuttingConcerns/3-programming-secure-extensions.rst
Documentation/About.rst
Documentation/b-ExtbaseReference/Index.rst
Documentation/c-FAQ/Index.rst

See TYPO3-Documentation/T3DocTeam#174 for details.

[TASK] Update hints of Extension Builder

---

Documentation/4-FirstExtension/3-create-the-domain-model.rst

A constructor does not have a return type.

[TASK] Remove return type from model constructor

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

[BUGFIX] Correct layout of query settings table

---

Documentation/10-Outlook/6-dispatching.rst
Documentation/3-BlogExample/11-Alternative-route-creating-a-new-posting.rst
Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/8-Fluid/10-template-creation-by-example.rst
Documentation/8-Fluid/2-using-different-output-formats.rst
Documentation/About.rst
Documentation/c-FAQ/Index.rst

Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#295
Releases: main, 11.5

[TASK] Correct spelling of TYPO3 versions

---

Documentation/b-ExtbaseReference/Index.rst

refs https://forge.typo3.org/issues/91671
resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/issues/464

Add example to forward to a different controller in v10
