Documentation/b-ExtbaseReference/Index.rst

Add the option with short description.
It's implemented at `\TYPO3\CMS\Extbase\Service\ExtensionService->getPluginNamespace()`

Add pluginNamespace option

---

Documentation/b-ExtbaseReference/Index.rst

This was missing in the documentation, I've added it from Patrick Lobacher Cheat sheets v 3.02.

Added missing feature "skipDefaultArguments"

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

* As validators won't get called for empty values anymore, this was a
breaking change and should be documented
Note: This was changed in some version. Perhaps we should annotate the version in some way.

[TASK] Add missing documentation for acceptsEmptyValues feature

---

Documentation/a-CodingGuidelines/Index.rst

As extbase now uses namespaces, this should be reflected in documentation.

Migrate Extbase class names

---

Documentation/8-Fluid/10-template-creation-by-example.rst

* As the old reference 'fluid-using-layouts' was not there, I've linked
it to 'creating-a-consistent-look-and-feel-with-layouts'
* This prevents the warning while rendering the documentation

[BUGFIX] Fix wrong reference

---

Documentation/0-Introduction/4-typographic-conventions.rst
Documentation/3-BlogExample/4-and-action.rst
Documentation/3-BlogExample/7-Paths-on-the-Data-Map.rst
Documentation/4-FirstExtension/3-create-the-domain-model.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/8-Fluid/1-basic-concepts.rst
Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst
Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

* Streamline inline code highlighting to use single back tics instead of
:code: and single back ticks, as code is the default role
* Also use spaces instead of tabs in those files, to follow PSR2

[CLEANUP] Remove old code syntax

---

Documentation/1-Installation/3-configuring-your-ide.rst

If you don't wish to remove "in first place", another option would be to change "in first place and" to "in the first place, as well as".

Minor grammatical fixes

---

Documentation/4-FirstExtension/4-make-products-persistent.rst

The CREATE STATEMENT for the relation tx_inventory_domain_model_product ends with KEY PARENT (pid), ); The last comma must not be there.
Despite that it is a good habit not to close the PHP.tag unless it is necessary to avoid the possible bug "headers already sent".

Adjusted a CREATE STATEMENT and PHP-Code

---

Documentation/6-Persistence/2-configure-the-backends-inputforms.rst

Original link: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/6-Persistence/2-configure-the-backends-inputforms.html

Correctly indent example TCA PHP (persistence/configure..backends..input..

---

Documentation/8-Fluid/1-basic-concepts.rst

PostController function indexAction assigns 'blogTitle' and 'blogPosts', but its Fluid template example misspells both object accessors as 'blog.Title' and 'blogPost', creating confusion. The following narrative uses 'blogTitle' explicitly.

Correct object accessor spellings in Fluid example

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

I corrected the three entries I found that only had one ":"

QueryInterface:ORDER_ASCENDING needs two ":"

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

using the documented values for ORDER_ASCENDING and ORDER_DESCENDING i ran into errors. I found out it was because the QueryInterface is found at ``\TYPO3\CMS\Extbase\Persistence\QueryInterface`` not at ``\TYPO3\CMS\Extbase\Persistence\Generic\QueryInterface``

Removed "Generic" from QueryInterface namespace

---

Documentation/6-Persistence/4-use-foreign-data-sources.rst

Removing leading \ from namespace in persistence class mapping demonstration

Persistence class mapping without leading \ in namespace

---

Documentation/4-FirstExtension/3-create-the-domain-model.rst

Having a backslash at the end accidentally escapes the semicolon instead of being a proper identifier.

Fix syntax error in code example

---

Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst

The prefixed backslashes in namespace are wrong.

[Doc] Remove wrong prefixed backslashes

---

Documentation/8-Fluid/9-using-php-based-views.rst

Removes leading backslash in namespace declaration

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

The core team decided, that the default language when creating a new record with Extbase is 0 and not -1 or the the current frontend language. https://review.typo3.org/#/c/41595/

Fix documentation for Extbase language handling on creating new records

---

Documentation/b-ExtbaseReference/Index.rst

Add documentation for feature option pageNotFoundOnCHashError, available
via TypoScript.

TASK: Add non documented extbase typoscript feature option

---

Documentation/b-ExtbaseReference/Index.rst

Explain the inheritance of classes to the reader so he is not forced to open the PHP classes about it.

settings and AbstractController

---

Documentation/10-Outlook/3-Command-controllers.rst

Especially for beginners it is important to mention that the extension has to be re-installed so that the controller is available on the CLI.

Add tip to re-installation of extension

---

Documentation/6-Persistence/1-prepare-the-database.rst

Removed the quotation marks from the default values for integers, since this could lead to issues in newer MySQL versions.

Removed quotation marks from default integers

---

Documentation/10-Outlook/2-Backend-modules.rst
Documentation/10-Outlook/3-Command-controllers.rst
Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
Documentation/4-FirstExtension/7-configuring-the-plugin.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/b-ExtbaseReference/Index.rst

As $_EXTKEY is more or less deprecated and will be removed in the
future. It's recommended to use the extension key as a string.
Therefore all examples were adjusted, including all mentions of the
variable.

TASK: Fix $_EXTKEY usage in docs

---

Documentation/b-ExtbaseReference/Index.rst

Change old and obsolete `@dontvalidate` to `@ignorevalidation`.
Need to be adjusted in versions from 6.2 on.

Change wrong annotation

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

Only tt_content has these broken field names, this error should not be copied in custom extensions.
l10n = localization
i18n = internationalization
l18n = historical error

[BUGFIX] Fix bogus l18n_* field suggestion

---

Documentation/8-Fluid/2-using-different-output-formats.rst

I think a found a little inaccuracy in the example typoscript.

adding tx prefix to extkey in the storage id line

---

Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst

[Section: Modeling the Class Hierarchy, Topic: Single Table Inheritance]
Removed prefixed \ (backslashes) of classnames on TS-configuration "config.tx_extbase.persistence.classes" otherwise it does not work.
(TYPO3 CMS v8.7.19)

Fixed TypoScript-Configuration

---

Documentation/b-ExtbaseReference/Index.rst

As it states in [Changelog/8.5/Breaking-78002](https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.5/Breaking-78002-EnforceCHashArgumentForExtbaseActions.html), `requireCHashArgumentForActionArguments` can be used per plugin

[FIX] Remove false note about requireCHashArgumentForActionArguments

---

Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst

Without this information I could not write a ViewHelper class. It always ended up in an Exception:
Uncaught TYPO3 Exception
Method AFM\Registeraddress\ViewHelpers\GetCaptchaViewHelper::render() does not existReflectionException thrown in file
/home/opaque/domains/mydomain/typo3_src-8.7.19/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php in line 571.72 ReflectionMethod::__construct("AFM\Registeraddress\ViewHelpers\GetCaptchaViewHelper", "render")/home/opaque/domains/mydomain/typo3_src-8.7.19/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php:00569:         $this->dataCacheNeedsUpdate = true;
00570:         if (!isset($this->methodReflections[$className][$methodName])) {00571:             $this->methodReflections[$className][$methodName] = new …

CompileWithRenderStatic

---

Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst

[Issue #229](https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/issues/229)
replacing
`TYPO3\CMS\Fluid\Core\ViewHelper` by
`TYPO3Fluid\Fluid\Core\ViewHelper`
as the former classes are being marked as deprecated in T3v9

Correct deprecated use statements in examples

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

When extending an AbstractValidator isValid($value) has to be implemented as it is abstract. validate($value) automatically calls isValid($value)
See: https://api.typo3.org/typo3cms/current/html/class_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_validation_1_1_validator_1_1_abstract_validator.html#a72063d2e922edda5321b1970297eb0c3

Extending from AbstractValidator

---

Documentation/6-Persistence/2-configure-the-backends-inputforms.rst

\TYPO3\CMS\Extbase\Persistence\Repository replace-function got removed since update to TYPO3 7.x. it doesn't exist in 8.7 anymore. see:
https://api.typo3.org/typo3cms/8/html/class_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_persistence_1_1_repository.html#a4872b38b18e2db4036b0c95708990ee6

Repository replace() got removed since TYPO3 7.x

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

'execute' is a function and there is no fetchRows() in Doctrine\DBAL\Driver\Mysqli\MysqliStatement
https://www.doctrine-project.org/api/dbal/2.8/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.html

Fix queryBuilder code example

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

at least  in version 8.7.24 you should not redefine the validate() but the isValid() method. 
Otherwise your validation will not work: 
* you miss $this->result so $this->result->addError() will fail in $this->addError()
* validate() returns wrong type

relevant method has changed in abstract class

---

Documentation/10-Outlook/3-Command-controllers.rst

To reduce duplicate information throughout the documentation, this commit
removes chapter on command controllers and points to "TYPO3 Explained".
Some of the information will be migrated to "TYPO3 Explained" in another
pull request.
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/468

Remove chapter about command controllers

---

Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst

change namespace due breaking change: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/9.0/Breaking-82414-RemoveCMSBaseViewHelperClasses.html

Change namespace from Fluid

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst

Trailing slash for function parameters raise a parse error. 
https://wiki.php.net/rfc/revisit-trailing-comma-function-args

Remove trailing slash

---

Documentation/4-FirstExtension/5-controlling-the-flow.rst

I believe it is a typo in the documentation ([https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/4-FirstExtension/5-controlling-the-flow.html]), and I think the author meant "defined" (instead of "declined").

Fix typo in 5-controlling-the-flow.rst

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/b-ExtbaseReference/Index.rst

See Changelog:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.1/Deprecation-88995-CallingRegisterPluginWithVendorName.html

Use extension key for configurePlugin and registerPlugin

---

Documentation/6-Persistence/4-use-foreign-data-sources.rst

The comma after `Person::class` is mandatory for valid PHP code.

Add missing comma in code example

---

Documentation/10-Outlook/3-Command-controllers.rst

Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/112
Releases: 9.5, 8.7

Add note to point out deprecation of Extbase Command Controllers (9.5)

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

This commit intends to improve the overall readability of the Validating Domain Objects page.
- Improve overall readability making it easier to read and hopefully understand.
- Remove any uses of the phrase "so called" when introducing the reader to new items
- Capitalise the word Extbase

Improve readability of Validating Domain Objects page

---

Documentation/b-ExtbaseReference/Index.rst

$viewObjectNamePattern isn't there anymore since TYPO3 7.0

Remove $viewObjectNamePattern

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

If I am right there is no f.form.textbox Viewhelper. It should be f.form.textfield for "title" and f.form.textarea for "description" instead.

Use correct ViewHelpers

---

Documentation/8-Fluid/2-using-different-output-formats.rst

additionalHeaders are defined as an array of header configurations. See https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Config/Index.html#additionalheaders 
Therefore the example doesnt work as before. Can be merged to LTS 10 and 9

correct additional header

---

Documentation/b-ExtbaseReference/Index.rst

See Deprecation 89868
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845

[TASK] Remove requireCHash feature toggle

---

Documentation/b-ExtbaseReference/Index.rst

[TASK] Remove $actionMethodName property from API

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

It seems, that TCA type select need a renderType definition. 
Otherwise you got "Unknown type: select, render type: select" in Backend View in TYPO3 10.4.12

add renderType definition to TCA language fields

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

If you copy the code, the code is added in more than one line. 
This could lead to errors and confusion if there is no error output. Especially for beginners

Delete spaces in TCA example

---

Documentation/6-Persistence/2a-creating-the-repositories.rst
Documentation/6-Persistence/3-implement-individual-database-queries.rst

Backport: 10.4, 9.5
https://wiki.typo3.org/Default_Orderings_and_Query_Settings_in_Repository
refs TYPO3-Documentation/T3DocTeam#154

Migrate Wiki content: Default_Orderings_and_Query_Settings_in_Repository

---

Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst

In paragraph before TCA code example fields "l10n_parent" "l10n_diffsource" are dicribed.
But in code example "l18n_parent" and "l18n_diffsource" is used. But this fields only used for tt_content table.
Changed naming of TCA fields to "l10n_parent" and "l10n_diffsource".

change naming off TCA field for language parameter

---

Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst

RegisterPlugin should be called in tt_content.php TCA-Overrides, not in ext_tables.php, based on the comment of registerPlugin of the ExtensionUtility and the fact, that it only changes the tt_content TCA in the end.
Releases: master, 10.4

Use registerPlugin in TCA Overrides

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

This fixes rendering of the list "directly in the model via" on https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/9-CrosscuttingConcerns/2-validating-domain-objects.html#domain-model-with-user-defined-validator-class (towards the end of the paragraph)

[BUGFIX] fix list rendering on "Validating Domain Objects"

---

Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst

* remove hint for TYPO3 10
* remove duplicate explanation
* remove TypoScript code, as only the PHP code is used in TYPO3 11 (afaik)

Update documentation: remove deprecated configuration example

---

Documentation/10-Outlook/6-dispatching.rst
Documentation/3-BlogExample/11-Alternative-route-creating-a-new-posting.rst
Documentation/3-BlogExample/4-and-action.rst
Documentation/4-FirstExtension/5-controlling-the-flow.rst
Documentation/5-Domain/2-implementing-the-domain-model.rst
Documentation/6-Persistence/2a-creating-the-repositories.rst
Documentation/6-Persistence/3-implement-individual-database-queries.rst
Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
Documentation/8-Fluid/10-template-creation-by-example.rst
Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst
Documentation/CodeSnippets/StyleguideCode/ValidatorInterface.rst.txt
Documentation/b-ExtbaseReference/Index.rst
screenshots.json

[Deprecation] #94115 - Parameter Type Evaluation via DocBlock comments
[Deprecation] #94351 - ext:extbase StopActionException
These deprecations touch much of the same code and therefore have to be handled in a combined PR
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395

[Deprecation] #94115, #94351

---

Documentation/2-BasicPrinciples/1-Model-View-Controller-in-Extbase.rst
Documentation/3-BlogExample/11-Alternative-route-creating-a-new-posting.rst
Documentation/3-BlogExample/2-the-stations-of-the-journey.rst
Documentation/3-BlogExample/4-and-action.rst
Documentation/3-BlogExample/5-Get-Blog-from-the-Repository.rst

I got to read this documentation recently and came across several ugly mistakes.
This pull-request attempts to address the following issues that were found in the 'Introduction'-section of the HTML-docs:
- missing whitespace in the rst-sources that caused things like rst-comments showing up as visible content in the rendered HTML
- some duplicated content
releases: master, 11.5

Corrected mistakes in some rst-files

---

Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst

The example calls the method `createHtmlResponse`, which is undefined. 
This PR replaces the `createHtmlResponse ` with `$this->htmlResponse();`

Fix : undefined createHtmlResponse is called

---

Documentation/6-Persistence/1-prepare-the-database.rst

The information about using lowercase_underscore and the corresponding Extbase model mapped attributes is too hidden in this sentence.
This should be more prominent as info section

Make Extbase relevant SQL field names more prominent

---

Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst

Since redirects do not return anything, the documentation here has to be edited and return void instead.

Remove return statement when a redirect is used

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst

"Registrating" doesn't appear to be a word in the English language. 
Fix spelling: Registrating -> Registering

Fix spelling

---

Documentation/10-Outlook/5-error-action.rst
Documentation/10-Outlook/6-dispatching.rst
Documentation/8-Fluid/2-using-different-output-formats.rst
Documentation/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.rst
Documentation/Includes.rst.txt
Documentation/c-FAQ/Index.rst

The ambiguous :ts: text role has been removed to
not confuse the writer with typescript and typoscript.
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/181

[DOCS] Replace :ts: with :typoscript: text role

---

Documentation/4-FirstExtension/4-make-products-persistent.rst
Documentation/6-Persistence/2-configure-the-backends-inputforms.rst

Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185

[DOCS] Reference manual's start page with :doc:`<manual>:Index`

---

Documentation/4-FirstExtension/7-configuring-the-plugin.rst
Documentation/7-Controllers/2-Configuring-and-embedding-Frontend-Plugins.rst
Documentation/b-ExtbaseReference/Index.rst

This is a backport of #372 (cherry picked from commit 10597102a01b1dc772c3aa5263cb7c9eb88ef8d0) to `10.4`.
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92609-UseControllerClassesWhenRegisteringPluginsmodules.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082

Remove vendorName from plugin registration

---

Documentation/6-Persistence/3-implement-individual-database-queries.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/38
Additionally, `fetchAll()` is renamed to `fetchAllAssociative()` for compatibility
with DBAL 3.2:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96287-DoctrineDBAL32.html

[TASK] #96972 - Deprecate QueryBuilder::execute()

---

Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst

This fixes a rendering problem where the list is not rendered
as list.
Releases: master, 11.5

[TASK] Fix formatting for lists

---

Documentation/c-FAQ/Index.rst

It is discouraged to use this as it will be remove in the future,
see changelog
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.0/Important-82692-GuidelinesForExtensionFiles.html

[TASK] Remove $_EXTKEY

---

Documentation/c-FAQ/Index.rst

This section has been migrated to the Fluid syntax
page in TYPO3 Explained
Related: TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#536

[TASK] Remove section about comments

---

Documentation/Index.rst

The reason is:
- sjr_offers is one of 3 extensions used in this manual
- the information which example extensions is used is not so
relevant
- sjr_offers is outdated (only available up to 6.2) and should
ideally not be used at all
We cannot remove all references to sjr_offers since that is
too much woven into the examples, but we can remove it from the
start page for now.

[TASK] Remove information about sjr_offers from start page

---

Documentation/6-Persistence/1-prepare-the-database.rst

Related: TYPO3-Documentation/Changelog-To-Doc#139

[TASK] #98024 - Remove TCA option "cruser_id"
